# Generated by Django 2.2 on 2019-04-18 11:41

import booking.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photoshoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('introduction', ckeditor.fields.RichTextField(blank=True, verbose_name='introduction')),
                ('confirmation', ckeditor.fields.RichTextField(blank=True, verbose_name='confirmation')),
            ],
            options={
                'verbose_name': 'Photoshoot',
                'verbose_name_plural': 'Photoshoots',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('slug', models.CharField(default=booking.models.random_string, max_length=16, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('shoot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timeslots', to='booking.Photoshoot', verbose_name='shoot')),
                ('subject', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timeslot', to='booking.Subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'Timeslot',
                'verbose_name_plural': 'Timeslots',
                'ordering': ['shoot', 'time'],
            },
        ),
    ]
