# Generated by Django 3.2.5 on 2023-04-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_photoshoot_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=None, null=True, verbose_name='time'),
        ),
    ]
